# Generated by Django 4.2.5 on 2023-10-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_encryptedfile_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steganographyimage",
            name="encryption_key",
        ),
    ]
