# Generated by Django 4.2.5 on 2023-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_remove_steganographyimage_encryption_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptionKey",
        ),
        migrations.AddField(
            model_name="encryptedfile",
            name="content_type",
            field=models.CharField(default="application/octet-stream", max_length=100),
        ),
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_name",
            field=models.CharField(default="file", max_length=125),
        ),
    ]
