# Generated by Django 4.2.5 on 2023-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_delete_encryptionkey_encryptedfile_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_data",
            field=models.TextField(),
        ),
    ]
