# Generated by Django 4.2.5 on 2023-11-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_alter_encryptedfile_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_data",
            field=models.TextField(),
        ),
    ]
