# Generated by Django 4.2.5 on 2023-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_alter_encryptedfile_file_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedfile",
            name="content_type",
        ),
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_data",
            field=models.FileField(upload_to="files/"),
        ),
    ]
