# Generated by Django 4.2.5 on 2023-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0009_remove_encryptedfile_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedfile",
            name="file_data",
            field=models.FileField(upload_to="files"),
        ),
    ]
