# Generated by Django 4.2.5 on 2023-11-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0010_alter_encryptedfile_file_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encryptedfile",
            old_name="file_data",
            new_name="file",
        ),
    ]
