# Generated by Django 4.2.5 on 2023-11-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0012_delete_steganographyimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encryptedfile",
            options={"managed": False},
        ),
    ]
