# Generated by Django 4.2.5 on 2023-11-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0013_alter_encryptedfile_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="encryptedfile",
            table="apis_encryptedfile",
        ),
    ]
